coal:
  modeHeight: 60
  highestRatio: 0.022
  vRate: 2.8
  maxChain: 10

iron_ore:
  modeHeight: 40
  highestRatio: 0.0175
  vRate: 2
  maxChain: 10

gold_ore:
  modeHeight: 30
  highestRatio: 0.0075
  vRate: 2
  maxChain: 6
  knowledgePoint: 4

lapis_lazuli:
  modeHeight: 35
  highestRatio: 0.012
  vRate: 0.5
  maxChain: 10

emerald:
  modeHeight: 20
  highestRatio: 0.015
  vRate: 0.2
  maxChain: 5

diamond:
  modeHeight: 13
  highestRatio: 0.002
  vRate: 1.5
  maxChain: 5
  knowledgePoint: 1

redstone:
  modeHeight: 15
  highestRatio: 0.02
  vRate: 1.4
  maxChain: 10
