minableItems:

  coal:
    uniqueName: Vanilla_COAL
    modeHeight: 60
    highestRatio: 0.022
    vRate: 2.8
    maxChain: 10

  iron_ore:
    uniqueName: Vanilla_IRON_ORE
    modeHeight: 40
    highestRatio: 0.0175
    vRate: 2
    maxChain: 10

  gold_ore:
    uniqueName: Vanilla_GOALD_ORE
    modeHeight: 30
    highestRatio: 0.0075
    vRate: 2
    maxChain: 6

  emerald:
    uniqueName: Vanilla_EMERALD
    modeHeight: 20
    highestRatio: 0.015
    vRate: 0.2
    maxChain: 5

  diamond:
    uniqueName: Vanilla_DIAMOND
    modeHeight: 13
    highestRatio: 0.002
    vRate: 1.5
    maxChain: 5

  redstone:
    uniqueName: Vanilla_REDSTONE
    modeHeight: 15
    highestRatio: 0.02
    vRate: 1.4
    maxChain: 10

fishableItems:

  zako:
    defaultRatio: 1
    uniqueName: Vanilla_RAW_FISH
    ExpireHours: 6
    Sachi: 4